services:
  db:
    image: postgres:15
    container_name: mgbd_postgres
    environment:
      POSTGRES_DB: mgbd_liquibase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:4.27.0
   
    depends_on:
      - db
    volumes:
      - .:/liquibase/changelog
    command: >
      --changelog-file=db/changelog/db.changelog-master.yaml
      --url=jdbc:postgresql://db:5432/mgbd_liquibase
      --username=postgres
      --password=postgres
      --search-path=/liquibase/changelog
      update

volumes:
  pgdata: